export const siteConfig = {
  name: "神權崩壞：誰是最後的天命之子",
  shortName: "神權崩壞",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://godright.example.com",
  description:
    "《神權崩壞：誰是最後的天命之子》官方文創網站，整合小說閱讀、電子書商城、角色圖鑑、世界觀百科、閱讀大廳與會員系統。",
  contactEmail: "contact@godright.example.com",
  mainNav: [
    { title: "首頁", href: "/" },
    { title: "小說閱讀", href: "/novel" },
    { title: "電子書商城", href: "/shop" },
    { title: "角色圖鑑", href: "/characters" },
    { title: "世界觀百科", href: "/lore" },
    { title: "七界地圖", href: "/map" },
    { title: "閱讀大廳", href: "/hall" },
    { title: "會員中心", href: "/account" },
  ],
  footerLinks: [
    { title: "神權編年史", href: "/timeline" },
    { title: "場地總覽", href: "/locations" },
    { title: "物件總覽", href: "/artifacts" },
    { title: "角色關係圖", href: "/relationships" },
    { title: "購物車", href: "/cart" },
    { title: "我的下載", href: "/account/downloads" },
    { title: "登入", href: "/login" },
    { title: "註冊", href: "/register" },
    { title: "訂閱消息", href: "/newsletter" },
    { title: "隱私權政策", href: "/privacy" },
    { title: "服務條款", href: "/terms" },
    { title: "退款規則", href: "/refund" },
    { title: "著作權聲明", href: "/copyright" },
  ],
} as const;
