export const siteConfig = {
  name: "《神權崩壞：誰是最後的天命之子》官方網站",
  shortName: "神權崩壞",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://godright.example.com",
  description:
    "進入神權崩壞的七界宇宙，閱讀小說、探索角色、收藏電子書與 IP 周邊，追蹤天命之子的最新消息。",
  contactEmail: "contact@godright.example.com",
  mainNav: [
    { title: "首頁", href: "/" },
    { title: "小說閱讀", href: "/novel" },
    { title: "商城", href: "/shop" },
    { title: "百科", href: "/lore" },
    { title: "七界地圖", href: "/map" },
    { title: "角色", href: "/characters" },
    { title: "神榜", href: "/rankings" },
    { title: "勢力", href: "/factions" },
    { title: "會員", href: "/account" },
  ],
  footerLinks: [
    { title: "時間線", href: "/timeline" },
    { title: "場地總覽", href: "/locations" },
    { title: "物件總覽", href: "/artifacts" },
    { title: "角色關係", href: "/relationships" },
    { title: "購物車", href: "/cart" },
    { title: "我的下載", href: "/account/downloads" },
    { title: "登入", href: "/login" },
    { title: "註冊", href: "/register" },
    { title: "訂閱消息", href: "/newsletter" },
    { title: "隱私權政策", href: "/privacy" },
    { title: "服務條款", href: "/terms" },
    { title: "退款規則", href: "/refund" },
    { title: "著作權聲明", href: "/copyright" },
  ],
} as const;
